#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
  echo "incorrect paramaters. usage: $0 pas-version release"
  exit 1
fi

pas_version=$1
release=$2

release="$(basename "${release}" -release)"

kiln_file=~/workspace/p-runtime/Kilnfile.lock
(
  cd ~/workspace/p-runtime
  git fetch --all 2> /dev/null 1> /dev/null
  git co rel/${pas_version} 2> /dev/null 1> /dev/null
  git pull -r 2> /dev/null 1> /dev/null
  release_name="$(cat "${kiln_file}" | grep "${release}" -A 2 | grep name | awk '{print $3}')"
  release_version="$(cat "${kiln_file}" | grep "${release}" -A 2 | grep version | awk '{print $2}')"
  if [[ -z $release_name ]]; then
    echo "No release was found matching \"$2\""
    exit 2
  else
    echo "${release_name}": "${release_version}"
  fi
  git co - 2> /dev/null 1> /dev/null
)

