#!/bin/bash

echo "Installing Consul"

set +e
consul --version
consul_status=$?
set -e

if [ ${consul_status} -ne 0 ]; then
  wget https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_darwin_amd64.zip -O /tmp/consul.zip && \
  unzip /tmp/consul.zip -d /usr/local/bin
  rm /tmp/consul.zip
fi

echo "Starting up Postgres and Mysql"

set +e
brew services stop mysql  #brew services restart mysql usually does not work
set -e
brew services restart postgresql
brew services start mysql

echo "Configuring Postgres"
brew link postgresql --force
set +e
psql -U postgres -c "\l"
postgres_role_status=$?
set -e
if [ ${postgres_role_status} -ne 0 ]; then
  psql -d postgres -c "CREATE ROLE postgres WITH SUPERUSER LOGIN PASSWORD 'password';" 
fi

echo "Configuring Mysql"
sleep 5
set +e
mysql -U root 2>&1 | grep "Access denied"
mysql_already_configured=$?
set -e
if [ ${mysql_already_configured} -ne 0 ]; then
  mysql -u root -e "CREATE DATABASE IF NOT EXISTS routing_api_test;"
  mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"
else
  echo "That Access denied output you just saw is fine, it means you already configured mysql"
fi


